# Generated by Django 4.2.1 on 2023-11-22 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Encuestado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.SmallIntegerField()),
                ('sexo', models.CharField(max_length=20)),
                ('estado_civil', models.CharField(max_length=20)),
                ('semestre', models.SmallIntegerField()),
                ('correo_electronico', models.EmailField(default='sincorreo@electronico.com', max_length=254)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cuestionario.carrera')),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cuestionario.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.SmallIntegerField(choices=[(1, 'Muy en desacuerdo'), (2, 'En desacuerdo'), (3, 'Ni acuerdo ni desacuerdo'), (4, 'De acuerdo'), (5, 'Muy de acuerdo')])),
                ('encuestado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cuestionario.encuestado')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cuestionario.pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cuestionario.carrera')),
            ],
        ),
        migrations.AddField(
            model_name='encuestado',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cuestionario.grupo'),
        ),
    ]
